version: "3.9"
services:
  postgres-purchase:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "saga" # todo rename purchase (нужны 2 БД)
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

# todo пыталась разнести таблицы по 2м БД, но не получается запустить 2 БД на докере
#  postgres-account:
#    image: postgres:14.8-alpine3.18
#    environment:
#      POSTGRES_DB: "account"
#      POSTGRES_USER: "postgres"
#      POSTGRES_PASSWORD: "postgres"
#    volumes:
#      - .:/docker-entrypoint-initdb.d
#    ports:
#      - "5435:5435"

  # система конфигурации (хранит информацию о топиках, партициях и тд)
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test_topic:1:3"
    depends_on:
      - zookeeper
