version: "3.9"
services:
  postgres-purchase:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "purchase"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

  postgres-account:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "account"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"

  # система конфигурации (хранит информацию о топиках, партициях и тд)
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
