application:
  kafka:
    topic:
      purchase-creating: purchase_creating
      purchase-created: purchase_created
      purchase-rejected: purchase_rejected
      purchase-canceling: purchase_canceling
      purchase-canceled: purchase_canceled

server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/saga # todo ??? rename -> purchase + another host
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  jpa:
    hibernate:
      ddl-auto: create

