application:
  kafka:
    topic:
      purchase-creating: purchase_creating
      purchase-created: purchase_created
      purchase-rejected: purchase_rejected
      purchase-canceling: purchase_canceling
      purchase-canceled: purchase_canceled

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/account
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: account-group
      auto-offset-reset: earliest

  jpa:
    hibernate:
      ddl-auto: create

cashback:
  rate: 10
  hundred: 100
